<?= "<?php"; ?>


<?= $namespace != null ? "namespace " . $namespace . ";" : ""; ?>


class <?= $class; ?>Form <?= $extends != null ? "extends " . $extends : ""; ?>

{

    <?= $trait != null ? "use " . $trait . ";" : ""; ?>

<?php foreach ($columns as $column): ?>
    private function <?= $column['name']; ?>Field()
    {
        $element = new \Phalcon\Forms\Element\<?= $column['type']; ?>("<?= $column['name']; ?>");
        $element->setLabel("<?= $column['name']; ?>");

<?php if ($column['type'] == 'Select'): ?>
        $element->setOptions([]);
<?php endif; ?>
<?php if ($column['type'] == 'Text' && $column['size']): ?>
        $element->addValidator(new \Phalcon\Validation\Validator\StringLength([
            "max" => <?= $column['size']; ?>

        ]));
<?php endif; ?>

        return $element;
    }

<?php endforeach; ?>

}

